FROM s390x/ubuntu:zesty

ENV container docker

RUN apt-get update; apt-get install -y systemd

RUN ["/bin/bash", "-c", "(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;"]

RUN apt-get update; apt-get install -y glusterfs-client glusterfs-server glusterfs-common ntp lvm2 rsync xfsprogs iproute tar sudo attr wget nfs-common openssh-client thin-provisioning-tools module-init-tools

RUN mkdir -p /etc/glusterfs_bkp /var/lib/glusterd_bkp /var/log/glusterfs_bkp;cp -r /etc/glusterfs/* /etc/glusterfs_bkp;cp -r /var/lib/glusterd/* /var/lib/glusterd_bkp;cp -r /var/log/glusterfs/ /var/log/glusterfs_bkp;

# Adding script to move the glusterfs config file to location
ADD gluster-setup.service /etc/systemd/system/gluster-setup.service
RUN chmod 644 /etc/systemd/system/gluster-setup.service

# Adding script to move the glusterfs config file to location
ADD gluster-setup.sh /usr/sbin/gluster-setup.sh
RUN chmod 500 /usr/sbin/gluster-setup.sh

# To avoid the warnings while accessing the container
#RUN sed -i "s/LANG/\#LANG/g" /etc/locale.conf

# Configure LVM so that we can create LVs and snapshots
RUN sed -i.save -e "s#udev_sync = 1#udev_sync = 0#" \
  -e "s#udev_rules = 1#udev_rules = 0#" \
  -e "s#use_lvmetad = 1#use_lvmetad = 0#" /etc/lvm/lvm.conf

# Set password
RUN echo 'root:password' | chpasswd

# Set SSH public key
USER root

VOLUME [ "/sys/fs/cgroup", "/dev", "/run/lvm" , "/var/lib/heketi" ]

EXPOSE 111 245 443 24007 2049 8080 6010 6011 6012 38465 38466 38468 38469 49152 49153 49154 49156 49157 49158 49159 49160 49161 49162
RUN ln -s /etc/init.d/glusterfs-server /etc/init.d/glusterd
RUN systemctl disable nfs-common
RUN systemctl enable ntp 
RUN systemctl enable rpcbind 
RUN systemctl enable gluster-setup 
RUN systemctl disable glusterfs-server 
RUN systemctl enable glusterd

CMD ["/sbin/init"]
