FROM s390x/ubuntu:17.10


ENV BUILD_HOME=/build
ENV GOPATH=$BUILD_HOME/golang
ENV PATH=$GOPATH/bin:$PATH
ENV HEKETI_BRANCH="master"

RUN mkdir $BUILD_HOME $GOPATH && \
    apt-get update; apt-get install -y golang-glide golang-go git make && \
    mkdir -p $GOPATH/src/github.com/heketi && \
    cd $GOPATH/src/github.com/heketi && \
    git clone -b $HEKETI_BRANCH https://github.com/heketi/heketi.git && \
    cd $GOPATH/src/github.com/heketi/heketi && \
    glide install -v && sed -i '/linux_arm64_dist:/i linux_s390x_dist:\nGOOS=linux GOARCH=s390x $(MAKE) dist' Makefile &&  make && \
    cp heketi /usr/bin/heketi && \
    cp client/cli/go/heketi-cli /usr/bin/heketi-cli && \
    glide cc && \
    cd && rm -rf $BUILD_HOME && \
    apt-get -q -y remove git golang-glide golang-go make && \
    apt-get -q -y autoremove

ADD ./heketi.json /etc/heketi/heketi.json
ADD ./heketi-start.sh /usr/bin/heketi-start.sh
VOLUME /etc/heketi

RUN mkdir /var/lib/heketi
VOLUME /var/lib/heketi

# expose port, set user and set entrypoint with config option
ENTRYPOINT ["/usr/bin/heketi-start.sh"]
EXPOSE 8080

